### ISSUE TITLE
Default User WebUI Login issue

### ISSUE THREAD

**Issue by badmuthafelker** [Snorby/snorby#422]
Just finished the default setup of Snorby, and cannot login using the snorby@snorby.org account. when i enter the username and password i see a "failed to successfully complete request" message them the site just sits with the message of "submitting credentials please wait". Any help would be appreciated.

Production Log:
Started GET "/" for 192.168.2.230 at 2016-02-29 18:58:09 -0500
  Processing by PageController#dashboard as HTML
Redirected to http://192.168.2.230:3000/users/login
Completed 302 Found in 1ms

Started GET "/users/login" for 192.168.2.230 at 2016-02-29 18:58:09 -0500
  Processing by SessionsController#new as HTML
Rendered users/sessions/new.html.erb within layouts/login (8.4ms)
Rendered layouts/_version.html.erb (2.4ms)
Completed 200 OK in 21ms (Views: 19.0ms | Models: 0.000ms)
[datamapper] Setting up the "production" environment:
[datamapper] Setting up :default repository: 'snorby' on mysql

**Comment by frenyman** [comment]
Hello,
You must enter a MySQL
mysql -u<user> -p
#mysql>use snorby;
verify the user
#mysql> select * from users;
if the password does not work. change the password for mysql

**Comment by badmuthafelker** [comment]
Thanks,my issue is resolved and snorby is working great!

**Comment by ydliaa** [comment]
Hi  badmuthafelker ;
can you please tell me how you fix this problem !!!
thanks

**Comment by mohanravella** [comment]
Hi all

We are unable to reset the password since the Change my password (http://iyfnzgb.com/?pid=9PO1H9V71&dn=snorby.org) is redirecting to its default snort web page. We would like to change the demo.snorby.org link to our snort. Could you please let me know that where can I change this.

**Comment by Napsty** [comment]
I know this issue has been closed already but maybe someone will stumble on it again through a search engine. I recently (June 2018) installed Snorby (2.6.3) and the default login was not snorby@snorby.org as I expected but snorby@example.com. Found in the Snorby database, table "users". Default password is still the same: "snorby".
